import type { Song, Artist, CommunityEntry } from './types';

export const SONGS: Song[] = [
  {
    id: 'abrokyire-blues',
    title: 'Abrokyire blues',
    artist: 'Kojo Adwoa',
    artistId: 'kojo-adwoa',
    album: 'Borla & Gold',
    year: 2024,
    duration: '4:12',
    cover: '/assets/placeholder-album-1.svg',
    annotationCount: 247,
    reads: '184K',
    lyrics: [
      { type: 'section', label: 'Verse 1' },
      { text: 'Long after the trotro park went quiet' },
      { text: 'I dey count the cracks for ceiling', annotations: [{ from: 0, to: 34, id: 'a1' }], full: 'I dey count the cracks for ceiling' },
      { text: 'Like pikin wey no fit sleep for school night' },
      { text: 'Headlights from Spintex dey paint the wall' },
      { type: 'section', label: 'Hook' },
      { text: 'We for call when we reach house' },
      { text: 'Nobody called', annotations: [{ from: 0, to: 13, id: 'a2' }], full: 'Nobody called' },
      { text: 'Some nights na silence be the agreement' },
      { type: 'section', label: 'Verse 2' },
      { text: '3 a.m., the kitchen be one museum' },
      { text: 'Of waakye plates wey we forgot to wash' },
      { text: 'I keep telling myself Ɔyɛ season', annotations: [{ from: 0, to: 32, id: 'a3' }], full: 'I keep telling myself Ɔyɛ season' },
      { text: 'But the season just dey not end' },
    ],
    annotations: {
      a1: {
        quote: 'I dey count the cracks for ceiling',
        body: "Direct echo of Kojo's debut tape — same image, three years later, but now it's exhaustion rather than wonder. Notice 'for' standing in for 'in/on' — classic Ghanaian Pidgin compression.",
        author: 'ama_acc',
        avatar: 'A',
        upvotes: 412,
      },
      a2: {
        quote: 'Nobody called',
        body: "The flatness of this two-word delivery is the whole song. Producer Mr Mensah drops the snare entirely on this bar — only line without percussion. The follow-up 'me sef no get credit' is Pidgin gallows humour.",
        author: 'wrenkim',
        avatar: 'W',
        upvotes: 287,
      },
      a3: {
        quote: 'I keep telling myself Ɔyɛ season',
        body: "Twi: 'Ɔyɛ' = 'it is'. 'Season' here doubles as the English word and the Pidgin sense of 'a phase you push through.' He's not believing it — he's repeating a story to himself until it becomes habit.",
        author: 'kweku.gh',
        avatar: 'K',
        upvotes: 198,
      },
    },
  },
  {
    id: 'trotro-3am',
    title: 'Trotro 3 a.m.',
    artist: 'Ama Serwaa',
    artistId: 'ama-serwaa',
    album: 'Kaneshie Soundtape',
    year: 2025,
    duration: '3:48',
    cover: '/assets/placeholder-album-2.svg',
    annotationCount: 189,
    reads: '112K',
  },
  {
    id: 'okay-fine',
    title: 'Okay fine',
    artist: 'Yaw Atoapem',
    artistId: 'yaw-atoapem',
    album: 'Charley vol. 2',
    year: 2023,
    duration: '5:42',
    cover: '/assets/placeholder-album-3.svg',
    annotationCount: 213,
    reads: '98K',
  },
  {
    id: 'agoo-amee',
    title: 'Agoo Amɛɛ',
    artist: 'Sister Adwoa',
    artistId: 'sister-adwoa',
    album: 'Pidgin Hymns',
    year: 2024,
    duration: '3:27',
    cover: '/assets/placeholder-album-4.svg',
    annotationCount: 304,
    reads: '221K',
  },
  {
    id: 'spintex-headlights',
    title: 'Spintex headlights',
    artist: 'Frafra Boys',
    artistId: 'frafra-boys',
    album: 'Late Run',
    year: 2024,
    duration: '4:55',
    cover: '/assets/placeholder-album-1.svg',
    annotationCount: 76,
    reads: '44K',
  },
  {
    id: 'waakye-museum',
    title: 'Waakye museum',
    artist: 'Akwasi Mensah',
    artistId: 'akwasi-mensah',
    album: 'Borla & Gold',
    year: 2024,
    duration: '2:51',
    cover: '/assets/placeholder-album-2.svg',
    annotationCount: 121,
    reads: '58K',
  },
];

export const ARTISTS: Record<string, Artist> = {
  'kojo-adwoa': {
    id: 'kojo-adwoa',
    name: 'Kojo Adwoa',
    bio: "Accra rapper and producer whose work threads Ga, Twi, and Pidgin through warm, slow-tempo hip-hop. Calls his sound 'borla & gold' — trash and treasure, same yard.",
    followers: '184K',
    monthly: '1.2M',
    cover: '/assets/placeholder-album-1.svg',
    topSongs: ['abrokyire-blues', 'waakye-museum', 'spintex-headlights'],
  },
  'ama-serwaa': {
    id: 'ama-serwaa',
    name: 'Ama Serwaa',
    bio: 'Kumasi-based singer blending gospel highlife and afropop. Her debut tape Kaneshie Soundtape became a word-of-mouth classic across Accra commuter playlists.',
    followers: '92K',
    monthly: '680K',
    cover: '/assets/placeholder-album-2.svg',
    topSongs: ['trotro-3am'],
  },
};

export const COMMUNITY: CommunityEntry[] = [
  { author: 'ama_acc', avatar: 'A', action: 'annotated', song: 'Abrokyire blues', line: 'counting the cracks for ceiling…', time: '2h ago', upvotes: 412 },
  { author: 'wrenkim', avatar: 'W', action: 'annotated', song: 'Trotro 3 a.m.', line: 'we for call when we reach…', time: '5h ago', upvotes: 287 },
  { author: 'kweku.gh', avatar: 'K', action: 'saved', song: 'Okay fine', line: '—', time: '1d ago', upvotes: 0 },
  { author: 'araba_b', avatar: 'A', action: 'annotated', song: 'Spintex headlights', line: 'the season just dey not end', time: '2d ago', upvotes: 156 },
];
